In [ ]:
!python main.py \
    --gpu 0 \
    --RUN 0 \
    --branch_condition_input_components mlc \
    --trunk_input_components xyzd \
    --output_components xyzs \
    --N_pt 1000 \
    --N_iterations 1000 \
    --batch_size 16 \
    --learning_rate 0.001 \
    --dir_base_load_data ../data/sampled \
    --N_samples 3000 \
    --split_method random \
    --base_dir ../experiments \
    --branch_hidden_dim 128 \
    --trunk_hidden_dim 128 \
    --trunk_encoding_hidden_dim 128 \
    --fc_hidden_dim 128 \
 

Using backend: pytorch
Other supported backends: tensorflow.compat.v1, tensorflow, jax, paddle.
paddle supports more examples now and is recommended.
/usr/local/lib/python3.11/dist-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)


Model Parameters:
Device: cuda
Run Number: 0
Folder Name: Changed_RUN0_D3000_N1000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random
Iterations: 1000
Batch Size: 16
Learning Rate: 0.001
Number of Samples: 3000
Data Split Method: random
Branch Condition Input Components: mlc
Trunk Input Components: xyzd
Output Components: xyzs
Trunk Encoding Hidden Dimension: 128
Branch Hidden Dimension: 128
Trunk Hidden Dimension: 128
Fully Connected Hidden Dimension: 128
branch_condition_input_train.shape = (2400, 5)
branc

In [1]:
!python train_nf.py \
  --experiment_dir ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random \
  --sampled_npz ../data/sampled/Rpt0_N5000.npz \
  --split_npz ../data/npy/combined_3000_split_random_train_valid.npz \
  --device cuda:0 \
  --latent_dim 128 \
  --num_flows 4 \
  --epochs 1000

Encoding latents: 100%|████████████████████████| 38/38 [00:00<00:00, 135.61it/s]
[latent] absmax=12.293326  mean=5.001041  std=2.227427
Saved latent normalization stats to: ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/nf_latent_norm.pth
[NF] epoch 1/1000  nll=181.062500  skipped_batches=0
[NF] epoch 2/1000  nll=178.071055  skipped_batches=0
[NF] epoch 3/1000  nll=170.663563  skipped_batches=0
[NF] epoch 4/1000  nll=165.650720  skipped_batches=0
[NF] epoch 5/1000  nll=162.454604  skipped_batches=0
[NF] epoch 6/1000  nll=159.487741  skipped_batches=0
[NF] epoch 7/1000  nll=156.674669  skipped_batches=0
[NF] epoch 8/1000  nll=154.092368  skipped_batches=0
[NF] epoch 9/1000  nll=151.753919  skipped_batches=0
[NF] epoch 10/1000  nll=149.488571  skipped_batches=0
[NF] epoch 11/1000  nll=147.195285  skipped_batches=0
[NF] epoch 12/1000  nll=144.817357  skipped_batches=0
[NF] epoch 13/1000  nll=142.535970  skipped_batches=0
[NF

In [12]:
import numpy as np
split = np.load("/workspace/Point-DeepONet/data/npy/combined_3000_split_random_train_valid.npz")
print(split["valid"][:20])

['hor_456_9' 'hor_587_131' 'dia_147_418' 'ver_173_59' 'hor_78_81'
 'hor_319_569' 'hor_438_448' 'dia_19_95' 'dia_592_61' 'hor_114_525'
 'dia_545_290' 'ver_113_129' 'dia_77_81' 'dia_245_34' 'dia_533_485'
 'hor_476_432' 'ver_415_14' 'dia_247_616' 'ver_284_378' 'ver_107_291']


In [28]:
import numpy as np
tmp = np.load("/workspace/Point-DeepONet/data/sampled/Ext_Rpt0_N1000.npz")
a = tmp["a"][0]   # (N,9)
b = tmp["b"][0]   # (N,4)
d = a[:,3]
mask_in = np.isfinite(b).all(axis=1)

print("inside ratio:", mask_in.mean())
print("d stats inside:", d[mask_in].min(), d[mask_in].max())
print("d stats outside:", d[~mask_in].min(), d[~mask_in].max())

inside ratio: 0.5
d stats inside: -8.199246 -0.0
d stats outside: 0.108528994 69.9155


In [5]:
%matplotlib inline
!python generate_and_visualize.py \
  --experiment_dir ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random \
  --data_root /workspace/Point-DeepONet/data \
  --case_key hor_587_131 \
  --num_samples 10 \
  --viz_num 10 \
  --viz_component 3 \
  --grid_n 96 \
  --grid_extent 1.5 \
  --out_dir ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/gen_outputs

### RUNNING FILE: /workspace/Point-DeepONet/7.DesignGenPointDeepONet /generate_and_visualize.py
0.59470975 1.2878963
[sample 0] iso 0.0 out of range; using 1.200000
[OK] sample 0: saved ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/gen_outputs/hor_587_131_sample_000_grid.vtk and ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/gen_outputs/hor_587_131_sample_000_surface.vtk | sdf_min=0.5947, sdf_max=1.2879
0.59661615 1.28372
[sample 1] iso 0.0 out of range; using 1.200000
[OK] sample 1: saved ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/gen_outputs/hor_587_131_sample_001_grid.vtk and ../experiments/DesignGenPointDeepONet_RUN2_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/gen_outputs/hor_587_131_sample_001_surface.vtk | sdf_min=0.5966, sdf_max=1.2837
0.5944592 1.2818307
[s

In [5]:
import numpy as np
xyzdml = np.load('../data/npy/xyzdmlc.npz')
name = xyzdml.files[0]            # 아무거나 하나
d = xyzdml[name][:, 3]            # d column
print("d min/max:", d.min(), d.max())
print("neg ratio:", (d < 0).mean(), "pos ratio:", (d > 0).mean())
print("near zero ratio(|d|<1e-3):", (np.abs(d) < 1e-3).mean())

d min/max: -16.849657 -2.8076923e-09
neg ratio: 1.0 pos ratio: 0.0
near zero ratio(|d|<1e-3): 0.3188148411253681


In [10]:
import os

def patch_binary_vtk_header(src, dst=None, scan_bytes=5 * 1024 * 1024):
    """
    Patch non-standard legacy VTK dtype tokens (e.g., vtktypeint32) inside a BINARY .vtk
    by editing only the first `scan_bytes` bytes and keeping byte-length identical via padding.
    """
    if dst is None:
        dst = src.replace(".vtk", ".patched.vtk")

    mapping = {
        b"vtktypeint32":   b"int",          # 3
        b"vtktypeuint32":  b"unsigned_int", # 12
        b"vtktypeint64":   b"long",         # 4
        b"vtktypeuint64":  b"unsigned_long",
        b"vtktypefloat32": b"float",
        b"vtktypefloat64": b"double",
    }

    with open(src, "rb") as f:
        head = f.read(scan_bytes)
        tail = f.read()

    for k, v in mapping.items():
        if k in head:
            # pad to same length so we don't mess with any offsets/streaming
            v_padded = v + b" " * (len(k) - len(v))
            head = head.replace(k, v_padded)

    with open(dst, "wb") as f:
        f.write(head)
        f.write(tail)

    return dst

src = "/workspace/Point-DeepONet/data/VolumeMesh/6_247.vtk"
dst = patch_binary_vtk_header(src)
print("patched:", dst)

import pyvista as pv

m = pv.read(dst)
print(m)
print("n_points, n_cells:", m.n_points, m.n_cells)
print("point arrays:", list(m.point_data.keys())[:20])
print("cell arrays:", list(m.cell_data.keys())[:20])

ERROR:root:Unsupported data type: vtktypeint32
2026-03-04 12:18:16.006 (3415.972s) [    73B667BA5000]      vtkDataReader.cxx:1968   ERR| vtkUnstructuredGridReader (0x1aa29620): Unsupported data type: vtktypeint32


patched: /workspace/Point-DeepONet/data/VolumeMesh/6_247.patched.vtk
UnstructuredGrid (0x73b576d839a0)
  N Cells:    127438
  N Points:   204869
  X Bounds:   -3.868e+01, 7.043e+01
  Y Bounds:   -1.638e+02, 2.080e+01
  Z Bounds:   2.363e-01, 6.534e+01
  N Arrays:   0
n_points, n_cells: 204869 127438
point arrays: []
cell arrays: []


In [14]:
import numpy as np

temp=np.load("/workspace/Point-DeepONet/data/npy/xyzdmlc.npz")
print(temp['ver_101_428'][0])

[ 54.80873   -24.9924     20.10018    -1.4042786   1.4644     35.58577
   0.          0.          1.       ]


In [17]:
import numpy as np

xy = np.load("../data/npy/xyzdmlc.npz")
tg = np.load("../data/npy/targets.npz")

keys_xy = set(xy.files)
keys_tg = set(tg.files)
print("xy keys:", len(keys_xy), "tg keys:", len(keys_tg), "intersection:", len(keys_xy & keys_tg))

k = next(iter(keys_xy & keys_tg))
print("sample key:", k)
print("xy[k].shape:", xy[k].shape, "tg[k].shape:", tg[k].shape)
print("xy first row:", xy[k][0])

xy keys: 6315 tg keys: 6315 intersection: 6315
sample key: dia_107_291
xy[k].shape: (211839, 9) tg[k].shape: (211839, 4)
xy first row: [ 39.28772   -62.2139      3.945469   -3.726697    1.61819    42.25812
  -0.669131    0.7431448   0.       ]


In [15]:
mesh= pv.read("/workspace/Point-DeepONet/data/VolumeMesh/6_247.vtk")

print(mesh.points)

ERROR:root:Unsupported data type: vtktypeint32
2026-03-04 12:57:09.934 (5749.901s) [    73B667BA5000]      vtkDataReader.cxx:1968   ERR| vtkUnstructuredGridReader (0x1d002e20): Unsupported data type: vtktypeint32


[[  48.45332  -156.116       2.655359]
 [  47.86765  -156.403       1.831782]
 [  48.44365  -156.691       2.154048]
 ...
 [  40.36466  -146.702       5.1335  ]
 [   1.296092    3.04238     5.1335  ]
 [  53.87648     4.491021    5.1335  ]]


In [3]:
import pyvista as pv

mesh = pv.read("../experiments/DesignGenPointDeepONet_RUN0_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/overall_vtks/dia_8_21.vtk")

print(mesh.point_data.keys())
print(mesh.cell_data.keys())


['gt_ux', 'gt_uy', 'gt_uz', 'gt_vm', 'pred_ux', 'pred_uy', 'pred_uz', 'pred_vm']
[]


In [ ]:
import pyvista as pv

pv.start_xvfb()                 # (리눅스/헤드리스에서) 가상 디스플레이 시작

mesh = pv.read("../experiments/DesignGenPointDeepONet_RUN0_D3000_N5000_branchinput_mlc_trunkinput_xyzd_output_xyzs_split_random/overall_vtks/dia_8_21.vtk")

print(mesh.point_data.keys())
print(mesh.cell_data.keys())


p = pv.Plotter(off_screen=True)
p.add_mesh(mesh, smooth_shading=True)


p.camera_position = "iso"
p.show(screenshot="./render.png")  # 창은 안 뜨고 render.png로 저장
print("saved: render.png")

/tmp/ipykernel_32315/3283150447.py:3: PyVistaDeprecationWarning: This function is deprecated and will be removed in future version of PyVista. Use vtk with osmesa instead.
  pv.start_xvfb()                 # (리눅스/헤드리스에서) 가상 디스플레이 시작


2026-03-04 11:23:32.025 ( 131.992s) [    73B667BA5000]    vtkX11Functions.cxx:194   WARN| Failed to load Xcursor library
2026-03-04 11:23:32.130 ( 132.097s) [    73B667BA5000]    vtkX11Functions.cxx:194   WARN| Failed to load Xcursor library


Widget(value='<iframe src="http://localhost:36945/index.html?ui=P_0x73b6604f7cd0_0&reconnect=auto" class="pyvi…

saved: render.png
